### PR TITLE
This adds KLEE as a fully buildable and working target.

### PR DESCRIPTION
**Pull request by horenmar**
Tried to split it into logically whole commits, but this means that not all of them compile by themselves.

Added a short README about dependencies for building the target.

### CODE REVIEW

**Comment by horenmar** [comment]
I fixed all of these, should I split them up again or just put all the fixes in a single commit?

**Comment by wentasah** [comment]
Update the original patches. Commit the fixes as separate patches and
them use fixup (or squash) operation in "git rebase -i" update the
original commit.

**Comment by horenmar** [comment]
Okay, these commits should have all the fixes integrated.

**Comment by horenmar** [comment]
Malloced memory is concrete, unless explicitly made symbolic.

**Pull request merged**
